const hre = require("hardhat");
const fs  = require("fs");
const path = require("path");

async function main() {
  console.log("🚀 Deploying PharmaChain contract...\n");

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deployer:", deployer.address);
  console.log(
    "Balance:",
    hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)),
    "ETH\n"
  );

  // Deploy
  const PharmaChain = await hre.ethers.getContractFactory("PharmaChain");
  const contract = await PharmaChain.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("✅ PharmaChain deployed to:", address);
  console.log("📦 Network:", hre.network.name);
  console.log("🔗 TxHash:", contract.deploymentTransaction().hash);

  // Save address + ABI to src/utils so React can pick it up automatically
  const deploymentData = {
    address,
    network:   hre.network.name,
    chainId:   hre.network.config.chainId,
    deployedAt: new Date().toISOString(),
  };

  // Write to blockchain/deployments/
  const deploymentsDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deploymentsDir)) fs.mkdirSync(deploymentsDir, { recursive: true });
  fs.writeFileSync(
    path.join(deploymentsDir, `${hre.network.name}.json`),
    JSON.stringify(deploymentData, null, 2)
  );

  // Also copy the ABI to src/utils/abi/ for React
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/PharmaChain.sol/PharmaChain.json"
  );
  const frontendDir = path.join(__dirname, "../../src/utils");
  if (!fs.existsSync(frontendDir)) fs.mkdirSync(frontendDir, { recursive: true });

  // Write contract address file for React
  const contractAddressFile = path.join(frontendDir, "contractAddress.js");
  fs.writeFileSync(
    contractAddressFile,
    `// Auto-generated by deploy.js — do not edit manually\nexport const CONTRACT_ADDRESS = "${address}";\nexport const CHAIN_ID = ${hre.network.config.chainId};\nexport const NETWORK_NAME = "${hre.network.name}";\n`
  );

  // Copy ABI
  if (fs.existsSync(artifactPath)) {
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    fs.writeFileSync(
      path.join(frontendDir, "PharmaChainABI.json"),
      JSON.stringify(artifact.abi, null, 2)
    );
    console.log("\n📋 ABI copied to src/utils/PharmaChainABI.json");
    console.log("📌 Address saved to src/utils/contractAddress.js");
  } else {
    console.warn("\n⚠️  Artifact not found yet — run `npm run compile` first.");
  }

  console.log("\n✨ Deployment complete!\n");
  console.log("Next: run `npm run seed` to assign roles and create sample batches.");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("❌ Deployment failed:", err);
    process.exit(1);
  });
